# Generated by Django 5.2.13 on 2026-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('broker', models.CharField(blank=True, default='', max_length=50, verbose_name='券商/平台')),
                ('account_type', models.CharField(choices=[('stock', '股票'), ('fund', '基金'), ('crypto', '虚拟货币'), ('futures', '期货')], max_length=20, verbose_name='投资类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='账户余额')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '投资账户',
                'verbose_name_plural': '投资账户',
                'db_table': 'investment_accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='持有数量')),
                ('avg_cost', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='平均成本')),
                ('current_price', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='当前价格')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '投资持仓',
                'verbose_name_plural': '投资持仓',
                'db_table': 'investment_holdings',
            },
        ),
        migrations.CreateModel(
            name='InvestmentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('transaction_type', models.CharField(choices=[('buy', '买入'), ('sell', '卖出')], max_length=10, verbose_name='交易类型')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='数量')),
                ('price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='价格')),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='手续费')),
                ('profit_loss', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='盈亏金额')),
                ('date', models.DateField(verbose_name='交易日期')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '投资交易',
                'verbose_name_plural': '投资交易',
                'db_table': 'investment_transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
