# Generated by Django 5.2.13 on 2026-04-21 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('investments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentholding',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='investments.investmentaccount', verbose_name='投资账户'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='holding',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='investments.investmentholding', verbose_name='持仓'),
        ),
        migrations.AddField(
            model_name='investmenttransaction',
            name='investment_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='investments.investmentaccount', verbose_name='投资账户'),
        ),
    ]
