# Generated by Django 5.2.13 on 2026-04-23 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0013_alter_assettype_user'),
        ('transactions', '0006_account_exclude_from_reports'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='fund_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_accounts', to='transactions.account', verbose_name='资金账户'),
        ),
    ]
