# Generated by Django 5.2.13 on 2026-04-23 13:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0014_investmentaccount_fund_account'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyHoldingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30, verbose_name='代码')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('date', models.DateField(verbose_name='日期')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='数量')),
                ('avg_cost', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='成本价')),
                ('close_price', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='收盘价')),
                ('previous_close', models.DecimalField(decimal_places=4, default=0, max_digits=15, verbose_name='昨收价')),
                ('market_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='市值')),
                ('cost_value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='成本')),
                ('daily_pl', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='当日盈亏')),
                ('total_pl', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='累计盈亏')),
                ('daily_pl_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='当日盈亏%')),
                ('total_pl_pct', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='累计盈亏%')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('holding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_snapshots', to='investments.investmentholding', verbose_name='持仓')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holding_snapshots', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '每日持仓快照',
                'verbose_name_plural': '每日持仓快照',
                'db_table': 'investment_daily_snapshots',
                'ordering': ['-date'],
                'unique_together': {('holding', 'date')},
            },
        ),
    ]
