# Generated by Django 5.2.13 on 2026-05-06 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0015_dailyholdingsnapshot'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='investmentholding',
            unique_together={('investment_account', 'symbol')},
        ),
    ]
