# Generated by Django 5.2.13 on 2026-05-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0016_holding_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentaccount',
            name='initial_investment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='初始投入金额'),
        ),
    ]
