# Generated by Django 5.2.13 on 2026-04-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='账户名称')),
                ('account_type', models.CharField(choices=[('cash', '现金'), ('bank', '银行卡'), ('alipay', '支付宝'), ('wechat', '微信'), ('other', '其他')], default='cash', max_length=20, verbose_name='账户类型')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='余额')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, default='#1677ff', max_length=20, verbose_name='颜色')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '账户',
                'verbose_name_plural': '账户',
                'db_table': 'accounts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='分类名称')),
                ('category_type', models.CharField(choices=[('income', '收入'), ('expense', '支出')], max_length=10, verbose_name='分类类型')),
                ('icon', models.CharField(blank=True, default='', max_length=50, verbose_name='图标')),
                ('color', models.CharField(blank=True, default='', max_length=20, verbose_name='颜色')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '分类',
                'verbose_name_plural': '分类',
                'db_table': 'categories',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('income', '收入'), ('expense', '支出'), ('transfer', '转账')], max_length=10, verbose_name='类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('date', models.DateField(verbose_name='日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '收支流水',
                'verbose_name_plural': '收支流水',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
