# Generated by Django 5.2.13 on 2026-04-21 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='预算金额')),
                ('period', models.CharField(choices=[('monthly', '月度'), ('yearly', '年度')], default='monthly', max_length=10, verbose_name='周期')),
                ('year', models.IntegerField(default=0, verbose_name='年份')),
                ('month', models.IntegerField(default=0, verbose_name='月份')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='transactions.category', verbose_name='分类（空=总预算）')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '预算',
                'verbose_name_plural': '预算',
                'db_table': 'budgets',
                'ordering': ['-period', 'category'],
            },
        ),
    ]
