# Generated by Django 5.2.13 on 2026-04-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_budget'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('cash', '现金'), ('bank', '银行卡'), ('credit_card', '信用卡'), ('alipay', '支付宝'), ('wechat', '微信'), ('other', '其他')], default='cash', max_length=20, verbose_name='账户类型'),
        ),
    ]
