# Generated by Django 5.2.13 on 2026-04-22 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exclude_from_reports',
            field=models.BooleanField(default=False, verbose_name='排除报表统计'),
        ),
    ]
