# Generated by Django 5.2.13 on 2026-05-12 20:46

from django.conf import settings
from django.db import migrations


def deduplicate_budgets(apps, schema_editor):
    """删除重复的预算记录，保留最新的"""
    Budget = apps.get_model('transactions', 'Budget')
    seen = set()
    duplicates = []
    for b in Budget.objects.order_by('-created_at'):
        key = (b.user_id, b.category_id, b.period, b.year, b.month)
        if key in seen:
            duplicates.append(b.id)
        else:
            seen.add(key)
    if duplicates:
        Budget.objects.filter(id__in=duplicates).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_account_exclude_from_reports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(deduplicate_budgets, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('user', 'category', 'period', 'year', 'month')},
        ),
    ]
