# Generated by Django 5.2.13 on 2026-04-21 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0004_alter_account_account_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('lend', '借出'), ('borrow', '借入')], max_length=10, verbose_name='类型')),
                ('counterparty', models.CharField(max_length=50, verbose_name='对方姓名')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='金额')),
                ('repaid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='已还金额')),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='利息')),
                ('status', models.CharField(choices=[('outstanding', '未还清'), ('partial', '部分归还'), ('settled', '已结清'), ('written_off', '已核销')], default='outstanding', max_length=15, verbose_name='状态')),
                ('date', models.DateField(verbose_name='日期')),
                ('expected_return_date', models.DateField(blank=True, null=True, verbose_name='预计归还日期')),
                ('reason', models.CharField(blank=True, default='', max_length=200, verbose_name='事由')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lending_records', to='transactions.account', verbose_name='关联账户')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lending_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '借贷记录',
                'verbose_name_plural': '借贷记录',
                'db_table': 'lending_records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repay_type', models.CharField(choices=[('collect', '收款'), ('repay', '还款')], max_length=10, verbose_name='还款类型')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='还款金额')),
                ('interest', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='其中利息')),
                ('date', models.DateField(verbose_name='还款日期')),
                ('note', models.CharField(blank=True, default='', max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='repayments', to='transactions.account', verbose_name='还款账户')),
                ('lending_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='lending.lendingrecord', verbose_name='借贷记录')),
            ],
            options={
                'verbose_name': '还款记录',
                'verbose_name_plural': '还款记录',
                'db_table': 'repayments',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
